[profile.default]
src = "contracts/"
out = "out"
libs = ["node_modules", "lib"]
fs_permissions = [{ access = "read-write", path = "./" }]
optimizer = true
optimizer-runs = 1
fuzz = { runs = 50, max_test_rejects = 100_000, seed = 0x5eed }
cache_path = './forge_cache'

[profile.ci]
fuzz = { runs = 256, max_test_rejects = 1_000_000 }

[rpc_endpoints]
bsc_mainnet = "${BSC_RPC_URL}"
local = "http://localhost:8545"

[etherscan]
bsc = { key = "${BSC_SCAN_API_KEY}", url = "https://api.bscscan.com/api" }
